[BUGFIX] Fix fatal PHP error
Fatal error: Cannot use TYPO3\CMS\Core\TypoScript\TypoScriptService as
TypoScriptService because the name is already in use in
t3forum/Classes/Configuration/ConfigurationBuilder.php on line 32.